name: Build & Publish Docker Image

on:
  release:
    types: [published]

jobs:
  # Push image to Docker Hub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Image Tag
        run: |
          TAG=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository.name }}:latest
          echo DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}

          # Change all uppercase to lowercase
          TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')

          # echo TAG to test
          echo TAG=$TAG

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}